dockversion: '3'

services:
  nginx:
    image: nginx:latest
    depends_on:
      trojan-helper:
        condition: service_completed_successfully
    container_name: trojan-nginx
    network_mode: host
  trojan:
    depends_on:
      - nginx
    image: teddysun/trojan-go:latest
    network_mode: host
    container_name: trojan
    volumes:
      - "trojan-data:/etc/trojan-go"
  trojan-helper:
    build: .
    image: trojan-helper:latest
    container_name: trojan-helper
    network_mode: host
    env_file:
      - .env
    volumes:
      - "trojan-data:/etc/trojan-go"

volumes:
  trojan-data: {}
