version: '3'

services:
  xui:
    image: enwaiax/x-ui:latest
    expose:
      - 54321
      - 443
  hello-world:
    depends_on:
      - xui
    build: .
    environment:
      - HOST=example.com
    image: marchocode/hello-world
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./conf.d:/etc/nginx/conf.d"

volumes:
  hello-world: {}
